### ISSUE TITLE
EXC_BAD_ACCESS on VideoFeed.swift line 104: session.addInput(videoDeviceInput)

### ISSUE THREAD

**Issue by waltersanford** [getbouncer/cardscan-ios#89] opened 2019-10-14 21:57 UTC
When trying to scan a credit card after using the camera, the video preview window appears empty and we get Thread 9: EXC_BAD_ACCESS (code=2, address=0x16db6fff8). The line of code that is failing is VideoFeed.swift, line 104: session.addInput(videoDeviceInput).

I've reproduced the error in CardScan - Example by adding a button that opens a standard UIImagePickerController. If you open the camera using the UIImagePickerController 3+ times and then tap the Scan Card button, the error will happen.

**Comment by kingst** [comment] 2019-10-14 22:20
Thanks for the bug report, Walter. We're on it.

@jaimejiyepark can you take a look?

**Comment by jaimejiyepark** [comment] 2019-10-14 22:20
taking a peek now! let me see if i can reproduce this.

**Comment by waltersanford** [comment] 2019-10-14 22:41
PR for fix is here: https://github.com/getbouncer/cardscan-ios/pull/90

**Comment by waltersanford** [comment] 2019-10-14 22:46
Here is the example app with the changes needed to take photos:
[Example.zip](https://github.com/getbouncer/cardscan-ios/files/3726676/Example.zip)

**Comment by jaimejiyepark** [comment] 2019-10-14 22:47
Thanks Walter! Taking a look now.

**Comment by jaimejiyepark** [comment] 2019-10-16 18:56
Hey @waltersanford ,
I was not able to reproduce your error with your example and with my own implementation with your description or the error.

**Comment by jaimejiyepark** [comment] 2019-10-16 19:26
Is there another way to reproduce the error?

**Comment by waltersanford** [comment] 2019-10-16 19:42
Interesting, I wonder if its device specific. What device are you testing on? I'll try it on several here.

**Comment by jaimejiyepark** [comment] 2019-10-16 20:09
I am testing on my iPhone 8 Plus + iOS13. How about you?

**Comment by waltersanford** [comment] 2019-10-16 20:19
Here is what I have so far:
iPhone Xs Max (13.1.2) - EXC_BAD_ACCESS
iPhone 6s Plus (12.4.1) - not happening

**Comment by waltersanford** [comment] 2019-10-16 20:43
I've updated that original iPhone Xs Max to 13.1.3 and I still get the error. I'll track down another similar device and see if I can reproduce it there.

**Comment by jaimejiyepark** [comment] 2019-10-16 22:47
I will also try to run it on an iPhone Xs Max. Will get back to you shortly.

**Comment by waltersanford** [comment] 2019-10-17 02:34
I just tried it on an iPhone Xs (13.1.2). I couldn't reproduce the crash in the same way but I was able to cause it to crash using a different set of steps: In my version of the Example app I opened the Scan window 3 times (tapping the Scan Card button, then the Back button) and then tapped the Take Photo button.

**Comment by waltersanford** [comment] 2019-10-17 02:45
Good news. Applying the fix in my PR fixes the second crash too. I'm calling it a second crash because it's also an EXC_BAD_ACCESS with code=2 but it doesn't have the same stack trace.

**Comment by waltersanford** [comment] 2019-10-17 03:10
So far it's only reproducible on the iPhone Xs and Xs Max. It doesn't happen on the iPhone 8, iPhone 6s Plus or the iPad Air 2.

**Comment by jaimejiyepark** [comment] 2019-10-23 20:01
Hey @waltersanford.
Sorry for taking so long getting back to you. After being able to reproduce your error and testing it ourselves, it looks like your fix works! Thank you and we will be closing this issue now.

**Closed by jaimejiyepark** 2019-10-23 20:01 UTC
