### ISSUE TITLE
Performance and memory leaks

### ISSUE THREAD

**Issue by sprzenus** [getbouncer/cardscan-ios#85] opened 2019-09-24 15:05 UTC
After dismissing the view my custom subclass of `ScanBaseViewController` is leaking. Moreover, after dismissing the view before it loads makes CPU usage be still on ~30% on a real device when I dismiss the view. I think removing memory leaks of the `ScanBaseViewController` would do the thing

**Comment by kingst** [comment] 2019-09-24 15:34
I think I can see what's going on with the memory leak, I'll take a look at this today.

**Comment by kingst** [comment] 2019-09-24 20:29
I can't seem to reproduce the 30% issue and when I run the library through the memory checker it looks like I'm only leaking two small objects (see screen shot below). Can you help me reproduce what you're seeing?

![image](https://user-images.githubusercontent.com/474745/65547909-3e84d500-decf-11e9-8097-c286a554973b.png)

**Comment by sprzenus** [comment] 2019-09-25 08:47
We push our controller on a navigation controller's stack and we leaking the view controller just after poping to the previous view controller. The issue with CPU usage happens when I exit the view before the white view disappears and the camera view appears

**Comment by kingst** [comment] 2019-09-25 13:11
Before I dig in deeper about these issues, why are you subclassing ScanBaseViewController? We have a number of UI customizations that we make available for our ScanViewController, although we don't have documentation for them yet you can see them in use in the [example app here](https://github.com/getbouncer/cardscan-ios/blob/f6819c795b0110347c3c384ab7dcea80dc1bd4ac/Example/CardScan/ViewController.swift#L114).

Are these UI customizations enough for what you're looking to do? If not, what's missing?

**Comment by sprzenus** [comment] 2019-09-25 15:20
Here you are: https://github.com/getbouncer/cardscan-ios/issues/74
We work on the same project

**Comment by kingst** [comment] 2020-01-29 21:31
closing this issue, please let us know if this is still a problem

**Closed** 2020-01-29 21:31 UTC
